<?php

/**
 * @file
 * Hooks for the datetime_extras module.
 */

use Drupal\Core\Extension\Exception\UnknownExtensionException;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function datetime_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.datetime_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Datetime Extras module provides additional functionality to extend the core Datetime and Datetime Range modules.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_field_widget_info_alter().
 *
 * Remove the daterange_duration widget unless a sufficiently modern version of
 * duration_field module is enabled.
 */
function datetime_extras_field_widget_info_alter(array &$info) {
  try {
    $duration_field_info = \Drupal::service('extension.list.module')->getExtensionInfo('duration_field');
    if (version_compare($duration_field_info['version'], '8.x-2.0-rc2', '<')) {
      // If we don't have 8.x-2.0-rc2 or later, hide the widget.
      unset($info['daterange_duration']);
    }
  }
  catch (UnknownExtensionException $e) {
    // Also hide the widget if there is no duration_field module at all.
    unset($info['daterange_duration']);
  }
}
