<?php

/**
 * @file
 * Hooks for the datetime_extras module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function datetime_extras_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.datetime_extras':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Datetime Extras module provides additional functionality to extend the core Datetime and Datetime Range modules.') . '</p>';
      $output .= '<h3>' . t('Displaying date/time ranges') . '</h3>';
      $output .= '<p>' . t('Date/time range fields can be displayed using the <em>Compact</em> field formatter on the field display settings page for any content type. If this formatter is used, you can choose a format from a predefined list that can be managed on the <a href=":daterange_format_list">Date and time range formats</a> page.', [':daterange_format_list' => Url::fromRoute('entity.daterange_compact_format.collection')->toString()]) . '</p>';
      $output .= '<h4>' . t('Examples') . '</h4>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Date only, start & end are within the same month') . '</dt>';
      $output .= '<dd>' . t('24-25 January 2017') . '</dd>';
      $output .= '<dt>' . t('Date only, start & end date are within the same year') . '</dt>';
      $output .= '<dd>' . t('29 January-3 February 2017') . '</dd>';
      $output .= '<dt>' . t('Date and time, start & end are both on the same day') . '</dt>';
      $output .= '<dd>' . t('9:00am-4:30pm, 1 April 2017') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_field_widget_info_alter().
 *
 * Remove the daterange_duration widget unless a sufficiently modern version of
 * duration_field module is enabled.
 */
function datetime_extras_field_widget_info_alter(array &$info) {
  if (!method_exists('\Drupal\duration_field\Service\DurationService', 'convertDateArrayToDateInterval')) {
    // If we don't have 8.x-2.0-rc2 or later, hide the widget.
    unset($info['daterange_duration']);
  }
}
