datetime_extras.daterange_compact_format.*:
  type: config_entity
  label: 'Date range format config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    default_pattern:
      type: string
      label: 'Default pattern'
    default_separator:
      type: string
      label: 'Separator'
    same_day_start_pattern:
      type: string
      label: 'Same day start pattern'
    same_day_end_pattern:
      type: string
      label: 'Same day end pattern'
    same_day_separator:
      type: string
      label: 'Same day separator'
    same_month_start_pattern:
      type: string
      label: 'Same month start pattern'
    same_month_end_pattern:
      type: string
      label: 'Same month end pattern'
    same_month_separator:
      type: string
      label: 'Same month separator'
    same_year_start_pattern:
      type: string
      label: 'Same year start pattern'
    same_year_end_pattern:
      type: string
      label: 'Same year end pattern'
    same_year_separator:
      type: string
      label: 'Same year separator'

field.widget.settings.daterange_duration:
  type: mapping
  label: 'Date range duration widget settings'
  mapping:
    default_duration:
      type: mapping
      label: 'Default duration'
      mapping:
        y:
          type: integer
          label: 'Years'
        m:
          type: integer
          label: 'Months'
        d:
          type: integer
          label: 'Days'
        h:
          type: integer
          label: 'Hours'
        i:
          type: integer
          label: 'Minutes'
        s:
          type: integer
          label: 'Seconds'
    duration_granularity:
      type: granularity
      label: 'Duration granularity'
    time_increment:
      type: integer
      label: 'Time increments'

field.formatter.settings.daterange_compact:
  type: mapping
  label: 'Date/time range compact display format settings'
  mapping:
    format_type:
      type: string
      label: 'Date/time range format'
